name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - master
    - cloud-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client
    - name: Add SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.GCP_VM_IP }}
    - name: Deploy to Google Cloud VM
      run: |
        ssh -o StrictHostKeyChecking=no username@${{ secrets.GCP_VM_IP }} << 'EOF'
        docker pull ahong89/reserv-bot:latest
        docker stop reserv-container || true
        docker rm reserv-container || true
        docker run -d --name reserv-container -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} ahong89/reserv-bot:latest
        EOF


